# Generated by Django 4.1.4 on 2022-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employee_mch_employee_mchc_employee_mcv_employee_pcv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hgb',
            field=models.FloatField(default='0', verbose_name='Количество гемоглобина'),
        ),
    ]
